### ISSUE TITLE
Help with R loop!

### ISSUE THREAD

**Issue by kbuzard** [kbuzard/political-uncertainty#3]
I've translated the meat of my simulation over to R, but the loop only hits 10 values instead of 1000. Would you take a look and see if it's obvious why? 1f9aea59914134bec4b23e8aa496a023addd1ac9

**Comment by fditraglia** [comment]
This code won't run at all for me: there seem to be a couple of syntax and logic errors so the loop doesn't execute at all. If you clear your environment with rm(list = ls()) and then re-run the code you should get the same error messages I'm getting.

I'm a little unclear on what this code is trying to accomplish, but here are a few things I spotted that seem to be wrong:

1. The variable BP5 is referred to on line 17 but hasn't been defined. This breaks several later lines.
2. Lines 38-40 are still in "Matlab" and need to be translated to R.

If you add some comments or type up a short pseudocode version it may be easier for me to see what's going on.

**Comment by kbuzard** [comment]
I think it's working now in commit c5bf4abcde01079517a83bd498bf1d7a6d41b1a1. 

I had no idea how to clear my environment, and no idea that old stuff would hang around like that (I'm used to SAS, which wipes everything out everytime you re-run a program), so thanks for the mini lesson, and SORRY! Also, sorry for not having commented it. It's been a long time since I shared code with someone.
