### ISSUE TITLE
raw_votes.dta?

### ISSUE THREAD

**Issue by JackRab** [kbuzard/political-uncertainty#6]
When trying to add more groups, one problem is that there is one data set, `raw_votes.dta`, missing in G drive's combined files folder, which is used in `11_groups_dummy_do.do`:
```
joinby using "${ROOT}\kristy\raw_votes.dta"
sort action_id politician_id OS_catcode
order action_id politician_id OS_catcode
```
Do you have any backup of this file?

**Comment by kbuzard** [comment]
I cannot find a copy of that file anywhere. It looks like it was only on Yusuf's machine and he didn't describe it in the documentation.

If you can't backward engineer it from the rest of the code and the output data sets, let me know and I will see if I can find contact information for Yusuf in Turkey. I think it's unlikely that he kept those files, but it would be worth trying to contact him and ask him.

**Comment by JackRab** [comment]
I don't know if it's possible to guess what he did, I will try my best. Could you please also try to contact him if you can? Thank you.

**Comment by kbuzard** [comment]
I've sent him an email. I'll let you know if I get a response.

**Comment by JackRab** [comment]
Thanks. I have done this part by myself though I don't guarantee what was done is backward engineered. The model is extended to include 32 groups right now. And it's easy to add more groups if needed since the code right now is quite general. It's great if we can get that data back and recheck it. But probably it doesn't matter that much.
